spring.datasource.url=jdbc:postgresql://ep-green-thunder-ayf0zp3k-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_JOIp02qRGytE
