spring.application.name=smart-procurement-system-backend

# Active profile
spring.profiles.active=local

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

